
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Aug 15 22:42:26 CEST 2022
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CONST = 6;
  public static final int NUMCONST = 48;
  public static final int LOWER = 42;
  public static final int GREATER = 40;
  public static final int LPAREN = 15;
  public static final int CONTINUE = 26;
  public static final int MINUS = 34;
  public static final int RPAREN = 16;
  public static final int COALESCE = 47;
  public static final int AND = 36;
  public static final int SEMICOLON = 8;
  public static final int RBOX = 11;
  public static final int RECORD = 14;
  public static final int LBRACES = 3;
  public static final int RBRACES = 4;
  public static final int OR = 37;
  public static final int COMMA = 5;
  public static final int CLASS = 12;
  public static final int INC = 27;
  public static final int DIV = 31;
  public static final int GEQ = 41;
  public static final int PLUS = 33;
  public static final int ASSIGN = 7;
  public static final int IF = 18;
  public static final int THIS = 45;
  public static final int EOF = 0;
  public static final int RETURN = 25;
  public static final int EQUAL = 38;
  public static final int SUPER = 44;
  public static final int NEW = 35;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MUL = 30;
  public static final int MOD = 32;
  public static final int IDENT = 51;
  public static final int BREAK = 24;
  public static final int VOID = 9;
  public static final int COLON = 17;
  public static final int ELSE = 19;
  public static final int STOP = 29;
  public static final int ENUM = 46;
  public static final int READ = 23;
  public static final int CHARCONST = 50;
  public static final int WHILE = 21;
  public static final int NEQUAL = 39;
  public static final int BOOLCONST = 49;
  public static final int EXTENDS = 13;
  public static final int LEQ = 43;
  public static final int LBOX = 10;
  public static final int DEC = 28;
  public static final int PRINT = 22;
  public static final int DO = 20;
}

